/**
 * Android backup rules (ARCHITECTURE.md §4a).
 *
 * WHY THIS PLUGIN EXISTS
 * ----------------------
 * The policy is: back up the SQLite database, do NOT back up the tile pack.
 *
 * The database is the user's own irreplaceable trip history and is roughly
 * 1-5 MB for a week. It is the answer to "my phone died on day 5", and it costs
 * nothing in privacy terms because device backups are encrypted.
 *
 * The tile pack is tens of megabytes, identical for every user, and
 * re-obtainable. Backing it up would waste the user's cloud quota — but the
 * real reason to exclude it is sharper than politeness: Android's auto-backup
 * has historically capped app data at around 25 MB, and a tile pack alone can
 * exceed that. When the cap is exceeded the *entire* backup can fail, silently,
 * taking the user's trip history with it. The asset we do not care about would
 * destroy the one we do.
 *
 * Two files are needed because Android changed the mechanism:
 *   - `fullBackupContent`     — Android 11 (API 30) and below
 *   - `dataExtractionRules`   — Android 12 (API 31) and above
 * Both are declared; the OS picks the one it understands.
 *
 * NOTE: `expo-sqlite` stores databases under `<filesDir>/SQLite/`, which is why
 * the include path is `SQLite/` in the `file` domain. If that ever changes,
 * this plugin silently stops backing up user data — so it is worth re-checking
 * on any major expo-sqlite upgrade.
 */

const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupRules.js - do not edit by hand. -->
<!-- Android 11 (API 30) and below. -->
<full-backup-content>
    <!-- The user's trip history. Small, and irreplaceable. -->
    <include domain="file" path="SQLite/" />

    <!-- Nothing to exclude. The map's tile packs and glyphs live in the CACHE
         directory (app/src/map/mapAssets.ts), which Android never backs up —
         so the 19 MB that could blow the auto-backup cap, and take the user's
         trip history down with it, is out of scope by construction rather than
         by a rule somebody has to remember to maintain. -->
</full-backup-content>
`;

const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupRules.js - do not edit by hand. -->
<!-- Android 12 (API 31) and above. -->
<data-extraction-rules>
    <cloud-backup>
        <include domain="file" path="SQLite/" />
    </cloud-backup>
    <device-transfer>
        <include domain="file" path="SQLite/" />
    </device-transfer>
</data-extraction-rules>
`;

function withBackupRuleFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (innerConfig) => {
      const xmlDir = path.join(
        innerConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml'
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'backup_rules.xml'),
        BACKUP_RULES_XML,
        'utf8'
      );
      fs.writeFileSync(
        path.join(xmlDir, 'data_extraction_rules.xml'),
        DATA_EXTRACTION_RULES_XML,
        'utf8'
      );
      return innerConfig;
    },
  ]);
}

function withBackupManifestAttributes(config) {
  return withAndroidManifest(config, (innerConfig) => {
    const application = innerConfig.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error(
        'withAndroidBackupRules: no <application> element in AndroidManifest.xml'
      );
    }

    application.$['android:allowBackup'] = 'true';
    application.$['android:fullBackupContent'] = '@xml/backup_rules';
    application.$['android:dataExtractionRules'] = '@xml/data_extraction_rules';

    return innerConfig;
  });
}

module.exports = function withAndroidBackupRules(config) {
  return withBackupManifestAttributes(withBackupRuleFiles(config));
};
