/**
 * Strip the development client's permissions from **release** builds (T-117a).
 *
 * WHY THIS EXISTS, AND IT IS NOT HYPOTHETICAL
 * -------------------------------------------
 * T-117a asked whether the development scaffolding is inert in a release build.
 * The first release APK this project ever produced (2026-08-18) answered it:
 * the scaffolding's *classes* are gone — no `expo-dev-launcher`, no ML Kit
 * barcode library — but **three of its permissions are not**, because they sit
 * in the app's own `AndroidManifest.xml` rather than in a library's:
 *
 *   - `SYSTEM_ALERT_WINDOW`   — "display over other apps"
 *   - `READ_EXTERNAL_STORAGE` (maxSdkVersion 32)
 *   - `WRITE_EXTERNAL_STORAGE` (maxSdkVersion 32)
 *
 * ⚠ **`SYSTEM_ALERT_WINDOW` is the one that matters.** It is the permission
 * screen-overlay malware needs, Play treats it as sensitive, and a user reading
 * the permission list of a **privacy-first walking app** finds *"display over
 * other apps"* sitting next to *"access location in the background"*. This app's
 * entire positioning is that it asks for exactly what it needs and nothing more
 * (D-044, CONTEXT §4.8). Shipping a permission it never uses undoes that in the
 * one place the user actually checks.
 *
 * The dev client genuinely needs it — that is what draws the dev menu over the
 * app — so it cannot simply be deleted from the shared manifest.
 *
 * HOW
 * ---
 * A `src/release/AndroidManifest.xml` with `tools:node="remove"`. The manifest
 * merger applies it to release builds only, so **debug keeps the dev menu and
 * release ships without the permission.**
 *
 * ⚠ Written by a config plugin rather than by hand, because `android/` is
 * generated: `npx expo prebuild` would silently discard a hand-edited file, and
 * the permission would return without anybody touching it. That is the same
 * failure mode as the `-gpu host` flag which kept its justification after the
 * thing it justified was deleted.
 *
 * ⚠⚠ **WHAT THIS DOES NOT FIX.** The same APK also carries
 * `com.google.android.c2dm.permission.RECEIVE`, from
 * **`com.google.firebase:firebase-messaging`**, pulled in by `expo-notifications`
 * — which this app uses for *local* notifications only (D-011). And
 * `BIND_GET_INSTALL_REFERRER_SERVICE`, from `com.android.installreferrer`.
 * Those come from inside a dependency, not from our manifest, and removing them
 * is a different and larger decision — see T-117c.
 */

// ⚠ `expo/config-plugins`, not `@expo/config-plugins` — the other plugins in
// this folder use the re-export and the scoped package is not a dependency here.
const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** Exactly the permissions the dev client adds and the product does not use. */
const REMOVE = [
  'android.permission.SYSTEM_ALERT_WINDOW',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
];

const MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withoutDevPermissions.js — do not edit by hand.

  Release-only overrides (T-117a). The development client needs these; the
  product never uses them, and SYSTEM_ALERT_WINDOW in particular is the one a
  user reads as "why does a walking app want to draw over my screen".
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
${REMOVE.map(
  (name) =>
    `    <uses-permission android:name="${name}" tools:node="remove" />`
).join('\n')}
</manifest>
`;

module.exports = function withoutDevPermissions(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'release'
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'AndroidManifest.xml'), MANIFEST, 'utf8');
      return cfg;
    },
  ]);
};
