/**
 * Ask Google Play services for the **latest** Maps renderer (T-147, D-057).
 *
 * WHY THIS IS NEEDED FOR GOOGLE'S OWN DARK MODE
 * ---------------------------------------------
 * `expo-maps` exposes `colorScheme: DARK`, which is Google's native night map —
 * the OEM one, styled and maintained by Google, and the thing the project lead
 * asked for. It is a **latest-renderer** feature. If Play services loads the
 * legacy renderer, the property is ignored in silence and the user gets a white
 * map after choosing dark.
 *
 * Which renderer loads is chosen by Play services **unless the app asks**, and
 * nothing in `expo-maps` asks: its Kotlin never calls `MapsInitializer`, which
 * is why logcat on this project said
 *
 *     MapsInitializer: preferredRenderer: null
 *     MapsInitializer: loadedRenderer: LEGACY
 *
 * on a device that may well have had the new one available. This plugin makes
 * the app state a preference, which is the documented way to opt in.
 *
 * ⚠ **A request, not a guarantee.** Where the new renderer is unavailable —
 * old Play services, some regions, this emulator possibly — Play services falls
 * back to legacy and the callback says so. That is why `map/googleNightStyle.ts`
 * still exists: it is the fallback for exactly those devices, and the reason it
 * must stay is visible in the log line this plugin prints.
 *
 * ⚠ **Why a plugin rather than an edit to `MainApplication.kt`.** `android/` is
 * generated by prebuild (CNG) and any hand edit is lost the next time somebody
 * runs it — silently, and the symptom would be dark mode regressing on a subset
 * of phones months later. The same reasoning as `withGoogleMapsApiKey.js`.
 */

const {
  withAppBuildGradle,
  withMainApplication,
} = require('expo/config-plugins');

/**
 * ⚠ The app module cannot see `MapsInitializer` without this.
 *
 * `expo-maps` pulls the Maps SDK in as its own `implementation` dependency,
 * which by design does **not** put it on the consuming module's compile
 * classpath. The symptom is one line — `Unresolved reference 'MapsInitializer'`
 * — at the point where the app tries to state a renderer preference.
 *
 * Pinned to the version Gradle already resolves for `expo-maps` (19.2.0), so
 * this adds a name to the classpath rather than a second copy of the library.
 * If expo-maps moves, this follows; a mismatch resolves to the higher of the
 * two and would be a silent upgrade nobody chose.
 */
const MAPS_DEPENDENCY =
  "    implementation 'com.google.android.gms:play-services-maps:19.2.0'";

const IMPORT = 'import com.google.android.gms.maps.MapsInitializer';

/**
 * Requested in `onCreate`, before any map exists.
 *
 * The renderer is chosen once per process and the choice is made by whoever
 * asks first; asking after a `MapView` has been created is too late, and Play
 * services would have already picked.
 *
 * The callback is not optional — the SDK requires one — and it is the only
 * place the app can learn which renderer it actually got. It goes to the log
 * rather than anywhere else on purpose: this is a fact about the device, it
 * matters exactly once, when somebody is asking why dark mode looks wrong.
 */
const INITIALISER = `    MapsInitializer.initialize(
      applicationContext,
      MapsInitializer.Renderer.LATEST
    ) { renderer ->
      android.util.Log.i("MadeiraExplorer", "Maps renderer: " + renderer.name)
      // ⚠ Written where JavaScript can read it (\`map/mapsRenderer.ts\`).
      //
      // Which renderer Play services actually gave us decides whether Google's
      // own dark map works at all, and that is a decision the UI has to make.
      // A one-word file in the app's own directory is the whole mechanism: no
      // native module, no bridge, no new dependency — and \`expo-file-system\`
      // is already here. It is rewritten on every launch because the answer can
      // change under the app when Play services updates.
      try {
        java.io.File(filesDir, "maps-renderer").writeText(renderer.name)
      } catch (error: Exception) {
        android.util.Log.w("MadeiraExplorer", "Could not record the renderer", error)
      }
    }
`;

module.exports = function withLatestMapsRenderer(config) {
  const withDependency = withAppBuildGradle(config, (mod) => {
    if (mod.modResults.contents.includes(MAPS_DEPENDENCY.trim())) {
      return mod;
    }

    mod.modResults.contents = mod.modResults.contents.replace(
      'dependencies {',
      `dependencies {
${MAPS_DEPENDENCY}`
    );
    return mod;
  });

  return withMainApplication(withDependency, (mod) => {
    let contents = mod.modResults.contents;

    if (contents.includes(IMPORT)) {
      // Prebuild runs this on an already-modified file often enough that
      // being idempotent is not optional — without this the import and the
      // call are appended again on every run until the file stops compiling.
      return mod;
    }

    contents = contents.replace(
      'import android.app.Application',
      `import android.app.Application\n${IMPORT}`
    );

    // Immediately after `super.onCreate()`, which is the first point at which
    // there is an application context to hand it.
    contents = contents.replace(
      '    super.onCreate()\n',
      `    super.onCreate()\n${INITIALISER}`
    );

    mod.modResults.contents = contents;
    return mod;
  });
};
