/**
 * After an app update, one notification asking for one tap (T-210).
 *
 * MEASURED ON THE P30, 2026-09-24. An update kills the app and its recorder.
 * With EMUI's launch management off, Android wakes the app for
 * `MY_PACKAGE_REPLACED`, but the recorder's foreground service may not be
 * started from the background (T-173), so recording stays off until the user
 * opens the app, which restores it at once. The project lead chose to ask for
 * that tap, and asked that the message read like a person wrote it.
 *
 * WHY NATIVE
 * ----------
 * The app's JavaScript runs after an update only if location events happen to
 * be queued; a receiver runs every time. It cannot read the app's database, so
 * the app leaves it `files/update-notice.json` (src/notify/updateNoticeFile.ts):
 * whether automatic recording is on, and the text in the user's language. No
 * file, or recording off, means no message.
 *
 * A plugin rather than an edit, because `android/` is generated (CNG).
 */

const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

const CLASS = 'UpdateNoticeReceiver';

function kotlinSource(pkg) {
  return `package ${pkg}

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationCompat
import org.json.JSONObject
import java.io.File

/**
 * Generated by plugins/withUpdateNotice.js (T-210). Do not edit here.
 *
 * After an update the recorder cannot restart itself from the background, so
 * this posts the one message, from the text the app left in
 * files/update-notice.json. Tapping it opens the app, which restarts the
 * recorder.
 */
class ${CLASS} : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    if (intent.action != Intent.ACTION_MY_PACKAGE_REPLACED) return
    try {
      val file = File(context.filesDir, "update-notice.json")
      if (!file.exists()) return
      val notice = JSONObject(file.readText())
      if (!notice.optBoolean("autoRecording", false)) return

      val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      val channelId = notice.getString("channelId")
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O &&
        manager.getNotificationChannel(channelId) == null
      ) {
        manager.createNotificationChannel(
          NotificationChannel(channelId, notice.getString("channelName"), NotificationManager.IMPORTANCE_DEFAULT)
        )
      }

      val launch = context.packageManager.getLaunchIntentForPackage(context.packageName) ?: return
      val tap = PendingIntent.getActivity(
        context, 0, launch, PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
      )
      val body = notice.getString("body")
      val notification = NotificationCompat.Builder(context, channelId)
        .setSmallIcon(context.applicationInfo.icon)
        .setContentTitle(notice.getString("title"))
        .setContentText(body)
        .setStyle(NotificationCompat.BigTextStyle().bigText(body))
        .setContentIntent(tap)
        .setAutoCancel(true)
        .build()
      manager.notify(NOTIFICATION_ID, notification)
      Log.i("Proa", "update notice posted")
    } catch (error: Exception) {
      Log.w("Proa", "update notice failed", error)
    }
  }

  companion object {
    const val NOTIFICATION_ID = 7210
  }
}
`;
}

module.exports = function withUpdateNotice(config) {
  const pkg = config.android?.package;
  if (typeof pkg !== 'string') {
    throw new Error('withUpdateNotice: android.package is not set');
  }

  const withSource = withDangerousMod(config, [
    'android',
    (mod) => {
      const dir = path.join(
        mod.modRequest.platformProjectRoot, 'app', 'src', 'main', 'java', ...pkg.split('.')
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${CLASS}.kt`), kotlinSource(pkg));
      return mod;
    },
  ]);

  return withAndroidManifest(withSource, (mod) => {
    const app = mod.modResults.manifest.application?.[0];
    if (app === undefined) return mod;
    app.receiver = app.receiver ?? [];
    const name = `.${CLASS}`;
    if (!app.receiver.some((r) => r.$?.['android:name'] === name)) {
      app.receiver.push({
        $: { 'android:name': name, 'android:exported': 'false' },
        'intent-filter': [
          { action: [{ $: { 'android:name': 'android.intent.action.MY_PACKAGE_REPLACED' } }] },
        ],
      });
    }
    return mod;
  });
};
