/**
 * The licences screen lists what actually ships (T-202, T-221).
 *
 *     cd app && npm test
 *
 * `legal/licences.json` is generated by `node tools/build-licences.mjs` from a
 * release build: the JavaScript bundle's source map and Gradle's release
 * classpath. These tests cannot rebuild it, so they hold the four ways it has
 * gone wrong or could: stale after a dependency change, build tools listed as
 * if they shipped (review N5), the Android half missing (review N5), and an
 * entry with no licence text to show.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

type Licence = {
  name: string;
  version: string;
  source: 'js' | 'android' | 'both';
  license: string;
  openSource: boolean;
  text: string | null;
  textRef?: string;
  url: string | null;
};
const document = JSON.parse(
  readFileSync(path.join(appRoot, 'src', 'legal', 'licences.json'), 'utf8')
) as { packageLock: string; texts: Record<string, string>; packages: Licence[] };
const names = new Set(document.packages.map((entry) => entry.name));

test('⚠ the list was generated from the dependencies the app has now', () => {
  // Replaces "every direct dependency is listed", which stopped being true on
  // purpose: a config plugin is a direct dependency and never ships. A changed
  // lock file means the build changed, so the list must be regenerated.
  const lock = createHash('sha256')
    .update(readFileSync(path.join(appRoot, 'package-lock.json')))
    .digest('hex');
  assert.equal(
    document.packageLock,
    lock,
    'package-lock.json changed. Build a release, then: node tools/build-licences.mjs'
  );
});

test('⚠ nothing that stays on the build machine is listed as shipping (review N5)', () => {
  // Each of these was on the screen until 2026-09-24, and none reaches a phone.
  const buildOnly = ['@babel/core', 'typescript', 'react-dom', 'react-native-web', 'expo-build-properties'];
  assert.deepEqual(buildOnly.filter((name) => names.has(name)), []);
});

test('⚠ the Android libraries are listed, not only the JavaScript (review N5)', () => {
  for (const name of [
    'androidx.core:core',
    'org.jetbrains.kotlin:kotlin-stdlib',
    'com.google.maps.android:maps-compose',
    'com.squareup.okhttp3:okhttp',
    'com.facebook.react:react-android',
  ]) {
    assert.ok(names.has(name), `${name} is missing`);
  }
  assert.ok(document.packages.filter((entry) => entry.source === 'android').length > 100);
});

test('every entry names its licence, and has something to show when opened', () => {
  const unnamed = document.packages.filter(
    (entry) => entry.license.trim() === '' || entry.license === 'UNKNOWN'
  );
  assert.deepEqual(unnamed.map((entry) => entry.name), []);

  const brokenRefs = document.packages.filter(
    (entry) => entry.textRef !== undefined && document.texts[entry.textRef] === undefined
  );
  assert.deepEqual(brokenRefs.map((entry) => entry.name), []);

  // The Apache terms ask to travel with the software: the shared copy must be
  // the whole licence, not a header.
  assert.match(document.texts['Apache-2.0'], /^Apache License/);
  assert.match(document.texts['Apache-2.0'], /END OF TERMS AND CONDITIONS$/);
});
