/**
 * The licences screen lists what actually ships (T-202).
 *
 *     cd app && npm test
 *
 * `legal/licences.json` is generated by `node tools/build-licences.mjs`. This
 * fails when a direct dependency is missing from it — a package added without
 * rerunning the tool — so the screen cannot quietly fall behind the app.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const manifest = JSON.parse(readFileSync(path.join(appRoot, 'package.json'), 'utf8')) as {
  dependencies: Record<string, string>;
};
const licences = JSON.parse(
  readFileSync(path.join(appRoot, 'src', 'legal', 'licences.json'), 'utf8')
) as { name: string; version: string; license: string; text: string | null }[];

test('⚠ every direct dependency is on the licences screen', () => {
  const listed = new Set(licences.map((entry) => entry.name));
  const missing = Object.keys(manifest.dependencies).filter((name) => !listed.has(name));
  assert.deepEqual(missing, [], `Rerun: node tools/build-licences.mjs\n${missing.join('\n')}`);
});

test('every entry names its licence', () => {
  const unnamed = licences.filter((entry) => entry.license.trim() === '' || entry.license === 'UNKNOWN');
  assert.deepEqual(unnamed.map((entry) => entry.name), []);
});
