/**
 * Write the app's icon files from the chosen design (T-257, A2, 2026-10-07).
 *
 *     cd tools && npm install            (once: the rasteriser, tools only)
 *     node tools/build-icon.mjs
 *     → app/assets/icon.png, android-icon-{foreground,background,monochrome}.png,
 *       notification-icon.png, splash-icon.png, app/src/ui/splashArt.ts, and
 *       site/icon.png (the website's icon, so bruma.lol shows the same one), and
 *       store/icon-512.png and store/feature-graphic.png (Play's listing, T-269)
 *
 * Then `npx expo prebuild --platform android` in `app/` turns them into the
 * launcher's mipmaps and the notification drawable.
 *
 * The art is `lib/icon-art.mjs`, the same module the options page drew, so the
 * icon that ships is the one the lead picked. Every layer is drawn on Android's
 * adaptive canvas (108 units, the middle 72 shown by the launcher's mask).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';
import { CANVAS, islandPaths, MADEIRA, optionFlag, PALETTE } from './lib/icon-art.mjs';
import { featureGraphicSvg } from './lib/feature-graphic.mjs';
import { rgbPng } from './lib/png-rgb.mjs';
import { mainIslandRings, ROUTE } from './lib/icon-geometry.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const assets = path.join(here, '..', 'app', 'assets');

const rings = mainIslandRings();
const icon = optionFlag(rings, ROUTE);

/** An SVG of `body` over the given view box, rendered to a square PNG of `size` pixels. */
function png(body, viewBox, size) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body}</svg>`;
  return new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng();
}

const FULL = `0 0 ${CANVAS} ${CANVAS}`;
/** What the launcher shows: the middle 72 of the 108 canvas. */
const SHOWN = '18 18 72 72';

/**
 * The notification's small icon: Android draws it as a white silhouette and
 * ignores every colour, so it is the island alone, filled white, as wide as
 * the canvas allows. A coloured icon there shows as a white square.
 */
const notification = (() => {
  const island = islandPaths(rings, 100, CANVAS / 2);
  return `<path d="${island.d}" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="3.2" stroke-linejoin="round"/>`;
})();

/**
 * The splash's still image: the icon as the launcher's circle, two thirds of
 * the canvas wide, transparent around it (Android 12 and later show a splash
 * icon through a circular mask of that size, so nothing is cut). **Without the
 * road:** the animated splash starts from this exact picture and lights the
 * road across it, so the handover from Android's still splash shows no jump.
 */
const splash = `<defs><clipPath id="c"><circle cx="54" cy="54" r="36"/></clipPath></defs>
  <g clip-path="url(#c)">${icon.background}${icon.withoutRoad}</g>`;

const files = {
  // Play Store and older launchers: the full square, edge to edge.
  'icon.png': png(`${icon.background}${icon.foreground}`, SHOWN, 1024),
  // Android 8+ adaptive layers, each on the whole 108 canvas.
  'android-icon-background.png': png(icon.background, FULL, 1024),
  'android-icon-foreground.png': png(icon.foreground, FULL, 1024),
  // Android 13+ themed icons: one colour, tinted by the system.
  'android-icon-monochrome.png': png(`<g fill="#FFFFFF">${icon.monochrome}</g>`, FULL, 1024),
  'notification-icon.png': png(notification, FULL, 96),
  'splash-icon.png': png(splash, FULL, 1024),
};

mkdirSync(assets, { recursive: true });
for (const [name, data] of Object.entries(files)) {
  writeFileSync(path.join(assets, name), data);
  console.log(`app/assets/${name}  ${data.length} bytes`);
}

// The website's tab and page icon: the launcher's square, small enough to load fast.
const siteIcon = png(`${icon.background}${icon.foreground}`, SHOWN, 256);
writeFileSync(path.join(here, '..', 'site', 'icon.png'), siteIcon);
console.log(`site/icon.png  ${siteIcon.length} bytes`);

// Play's listing (T-269): its 512 px icon, the launcher's square, and the
// feature graphic the lead picked (B, the flag).
const store = path.join(here, '..', 'store');
mkdirSync(store, { recursive: true });
const storeFiles = {
  'icon-512.png': png(`${icon.background}${icon.foreground}`, SHOWN, 512),
  // ⚠ No alpha: Play takes a feature graphic only as JPEG or 24-bit PNG.
  'feature-graphic.png': rgbPng(
    new Resvg(featureGraphicSvg(rings, ROUTE), { fitTo: { mode: 'width', value: 1024 } }).render()
  ),
};
for (const [name, data] of Object.entries(storeFiles)) {
  writeFileSync(path.join(store, name), data);
  console.log(`store/${name}  ${data.length} bytes`);
}

/**
 * The same icon as plain shapes, for the animated splash in the app
 * (`ui/AnimatedSplash.tsx`): generated, so the animation and the icon cannot
 * drift apart.
 */
const { parts } = icon;
const art = `/**
 * GENERATED by \`node tools/build-icon.mjs\`; do not edit. The launcher icon's
 * shapes (T-257, the lead's A2), for the animated splash.
 *
 * Drawing paths in the icon's own 108-unit canvas, like the stamp artwork:
 * not coordinates, names or bounds, which D-017 keeps out of \`app/\`.
 */

/** The adaptive icon canvas, in units; the launcher shows the middle 72. */
export const CANVAS = ${CANVAS};

export const COLOURS = {
  flagBlue: '${MADEIRA.flagBlue}',
  flagGold: '${MADEIRA.flagGold}',
  crossRed: '${MADEIRA.trimRed}',
  island: '${PALETTE.island}',
  road: '${PALETTE.road}',
  background: '${PALETTE.slate}',
} as const;

/** The cross of the Order of Christ: four arms, and the white cross inside. */
export const CROSS = {
  arms: ${JSON.stringify(parts.cross.arms)},
  lines: '${parts.cross.lines}',
  lineWidth: ${parts.cross.lineWidth.toFixed(3)},
} as const;

export const ISLAND = '${parts.island}';

export const ROAD = '${parts.road}';

/** The road's length in units: what the stroke animation draws, start to end. */
export const ROAD_LENGTH = ${parts.roadLength.toFixed(2)};
`;
const artPath = path.join(here, '..', 'app', 'src', 'ui', 'splashArt.ts');
writeFileSync(artPath, art);
console.log('app/src/ui/splashArt.ts');
