/**
 * Build the parts of bruma.lol that must not be written by hand (T-241).
 *
 *     node --disable-warning=MODULE_TYPELESS_PACKAGE_JSON tools/build-site.mjs
 *
 * `site/privacy.html` is generated from `app/src/legal/privacyPolicy.ts`, the
 * same source the app shows offline and `docs/privacy-policy.md` comes from.
 * A policy that says one thing in the app and another on the web is worse than
 * either, so nobody edits the HTML.
 *
 * It also checks every page for dash characters. The project lead reads them as
 * AI-written, and the app's own text is held to that by `i18n.test.ts`; the site
 * had no such guard. It exits non-zero if one slips in.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { CONTACT_EMAIL, POLICY_VERSION, policySections } from '../app/src/legal/privacyPolicy.ts';
import { APP_NAME } from '../app/src/brand.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const site = path.resolve(here, '..', 'site');

const escape = (text) =>
  text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const body = policySections()
  .map(
    (section) =>
      `  <h2>${escape(section.heading)}</h2>\n` +
      section.paragraphs.map((p) => `  <p>${escape(p)}</p>`).join('\n')
  )
  .join('\n');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${APP_NAME} Privacy Policy</title>
<link rel="stylesheet" href="style.css">
<link rel="icon" href="icon.png">
</head>
<body>
<!-- GENERATED by tools/build-site.mjs from app/src/legal/privacyPolicy.ts. Do not edit. -->
<main class="policy">
  <header>
    <h1>${APP_NAME} Privacy Policy</h1>
    <p class="tagline">Last changed: ${POLICY_VERSION}</p>
  </header>
${body}
  <a class="back" href="index.html">Back to ${APP_NAME}</a>
</main>
<footer>
  <span>&copy; 2026 ${APP_NAME}</span>
  <a href="index.html">Home</a>
</footer>
</body>
</html>
`;

writeFileSync(path.join(site, 'privacy.html'), html, 'utf8');
console.log(`site/privacy.html: ${policySections().length} sections`);

// The dash guard, over every page, visible text only (comments stripped).
let failed = false;
for (const file of readdirSync(site).filter((f) => f.endsWith('.html'))) {
  const text = readFileSync(path.join(site, file), 'utf8').replace(/<!--[\s\S]*?-->/g, '');
  const hits = text.split('\n').filter((line) => /[–—]/.test(line));
  if (hits.length) {
    failed = true;
    console.error(`✗ ${file} has a dash character:\n  ${hits.map((l) => l.trim()).join('\n  ')}`);
  }
}

if (CONTACT_EMAIL === null) {
  console.log('');
  console.log('⚠ CONTACT_EMAIL is null: no contact on the site yet. Play requires one (T-206).');
}

process.exit(failed ? 1 : 0);
