/**
 * The dark map style, held to D-015 (T-139, D-026).
 *
 *     cd app && npm test
 *
 * WHY A TEST FOR CARTOGRAPHY
 * --------------------------
 * The map is a MapLibre style — a JSON file of colours — and this project has
 * no eyes. That combination is exactly where D-015 gets lost: a dark style
 * wants everything dark, and the one rule D-015 states most plainly is that
 * **unvisited roads stay legible mid-grey and never near-black**, because a
 * road you cannot see is a road the user cannot tell they have not travelled.
 *
 * A style is regenerated by `tiles/style/generate.mjs` on every package bump
 * and flavor change, so the failure mode is not somebody choosing a bad colour
 * on purpose — it is a value drifting, or an upstream `DARK` default coming
 * through unoverridden, and nobody noticing because nobody can see it.
 *
 * This reads the **app's own copy** of the generated style — the file the
 * binary ships (`app/assets/map/dark.json`) — rather than the flavor source.
 * That way it fails if the generator stops applying an override, which is the
 * realistic regression.
 *
 * ⚠ **Contrast is a floor, not a verdict.** None of this says the map looks
 * good, and no test can. T-065 — outdoors, in Funchal, at midday, held at
 * arm's length — is the only judge whose verdict counts, and D-026 stays
 * Provisional until it happens.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { contrastRatio } from '../ui/contrast.ts';

const here = path.dirname(fileURLToPath(import.meta.url));

type Layer = {
  id: string;
  type: string;
  paint?: Record<string, unknown>;
};

function style(name: 'light' | 'dark'): { layers: Layer[]; name: string } {
  const file = path.resolve(here, '..', '..', 'assets', 'map', `${name}.json`);
  return JSON.parse(readFileSync(file, 'utf8'));
}

/**
 * A layer's flat colour, when it has one.
 *
 * Returns null for a data-driven expression — those are arrays, and a style
 * that starts using one for a road would need this test rewritten rather than
 * silently passing.
 */
function flatColour(layer: Layer, property: string): string | null {
  const value = layer.paint?.[property];
  return typeof value === 'string' && value.startsWith('#') ? value : null;
}

function layerColour(layers: Layer[], id: string, property: string): string | null {
  const layer = layers.find((candidate) => candidate.id === id);
  return layer === undefined ? null : flatColour(layer, property);
}

// ---------------------------------------------------------------------------
// The style is there at all
// ---------------------------------------------------------------------------

test('both styles ship, with the same layers', () => {
  // Probe check before anything else. If these files were missing or empty,
  // every assertion below would pass by finding nothing to check.
  const dark = style('dark');
  const light = style('light');

  assert.ok(dark.layers.length > 40, `only ${dark.layers.length} layers`);
  assert.equal(dark.layers.length, light.layers.length);
  assert.equal(dark.name, 'Madeira dark');
});

test('the ground is dark but never pure black', () => {
  // Pure black loses the hillshade entirely, and D-026 puts figure-ground in
  // the terrain. It also flares badly in sunlight, which is why the light
  // style's own note says the same thing about its paper.
  const earth = layerColour(style('dark').layers, 'earth', 'fill-color');
  assert.ok(earth !== null, 'the earth layer has no flat colour');
  assert.notEqual(earth.toLowerCase(), '#000000');
  assert.ok(contrastRatio(earth, '#000000') > 1.2, `${earth} is effectively black`);
});

// ---------------------------------------------------------------------------
// D-015: unvisited roads stay legible
// ---------------------------------------------------------------------------

test('every drawn road is legible against the ground', () => {
  // ⚠ THE RULE THIS FILE EXISTS FOR. D-015 forbids near-black roads outright.
  // Tunnels are excluded deliberately and separately below.
  const layers = style('dark').layers;
  const earth = layerColour(layers, 'earth', 'fill-color');
  assert.ok(earth !== null);

  // ⚠ **Ways the user could actually have travelled**, which is what D-015's
  // rule is about — a road you cannot see is a road you cannot tell you have
  // not travelled. Excluded, each for a stated reason rather than to make this
  // pass: `runway`/`taxiway` are the airport, kept as the trip-end landmark
  // (D-012) but not somewhere anyone walked; `rail` does not exist on the
  // island. **`pier` is NOT excluded** — a pier is walkable, and this test
  // found it at 1.07:1, effectively invisible, which is why it is now brighter.
  const notTravellable = /(runway|taxiway|rail)/;
  const roads = layers.filter(
    (layer) =>
      layer.id.startsWith('roads_') &&
      !layer.id.includes('casing') &&
      !layer.id.includes('tunnel') &&
      !notTravellable.test(layer.id) &&
      layer.type === 'line'
  );
  assert.ok(roads.length > 0, 'no road layers found — the probe is wrong');

  const failures: string[] = [];
  for (const road of roads) {
    const colour = flatColour(road, 'line-color');
    if (colour === null) {
      continue;
    }
    const ratio = contrastRatio(colour, earth);
    if (ratio < 3) {
      failures.push(`${road.id} ${colour} is ${ratio.toFixed(2)}:1`);
    }
  }

  assert.deepEqual(
    failures,
    [],
    'these roads are not legible against the ground (D-015: mid-grey, never near-black)'
  );
});

test('road casings are darker than the ground, so a road reads as a line', () => {
  const layers = style('dark').layers;
  const earth = layerColour(layers, 'earth', 'fill-color');
  assert.ok(earth !== null);

  const casings = layers.filter(
    (layer) => layer.id.includes('casing') && !layer.id.includes('tunnel')
  );
  assert.ok(casings.length > 0, 'no casing layers found');

  for (const casing of casings) {
    const colour = flatColour(casing, 'line-color');
    if (colour === null) {
      continue;
    }
    // Darker than the ground: a casing lighter than the ground would make the
    // road read as a trench rather than a line.
    assert.ok(
      contrastRatio(colour, '#000000') < contrastRatio(earth, '#000000'),
      `${casing.id} ${colour} is lighter than the ground`
    );
  }
});

test('tunnels are dimmer than surface roads, and that is deliberate', () => {
  // Not held to the legibility floor: GPS dies in a tunnel and the trace gaps
  // honestly there (D-032). A faint road continuing under the mountain is a
  // hint, not information the user acts on. This asserts the *intent* —
  // dimmer than the surface — so a later change that brightens them to match
  // is a decision rather than a drift.
  const layers = style('dark').layers;
  const surface = layerColour(layers, 'roads_minor', 'line-color');
  const tunnel = layers.find((layer) => layer.id.includes('tunnel') && !layer.id.includes('casing'));

  if (surface === null || tunnel === undefined) {
    return;
  }
  const tunnelColour = flatColour(tunnel, 'line-color');
  if (tunnelColour === null) {
    return;
  }

  assert.ok(
    contrastRatio(tunnelColour, '#000000') < contrastRatio(surface, '#000000'),
    `${tunnel.id} is not dimmer than the surface road`
  );
});

// ---------------------------------------------------------------------------
// The island has to read as an island
// ---------------------------------------------------------------------------

test('the airport is identifiable, even though it is not a road', () => {
  // It is where the trip ends and the reveal fires (D-012), so it has to be
  // findable on the map — but it is a landmark rather than a route, which is
  // why it is exempt from the road floor above and gets its own, lower bar.
  const layers = style('dark').layers;
  const earth = layerColour(layers, 'earth', 'fill-color');
  const runway = layerColour(layers, 'roads_runway', 'line-color');
  assert.ok(earth !== null);

  if (runway !== null) {
    const ratio = contrastRatio(runway, earth);
    assert.ok(ratio >= 2, `the runway is ${ratio.toFixed(2)}:1 — not findable`);
    assert.ok(ratio < 3, 'the runway is competing with the roads');
  }
});

test('sea and land are separable, and the terrain does the rest', () => {
  // ⚠ Only ~1.5:1, and deliberately. Two large adjacent fills read apart at
  // far less than text contrast, and **D-026 puts figure-ground in the shaded
  // terrain rather than in the fills.** An earlier attempt at this demanded
  // 2:1 and there was NO palette that also kept the roads legible — the
  // constraint was mine, not the design's.
  const layers = style('dark').layers;
  const earth = layerColour(layers, 'earth', 'fill-color');
  const water = layerColour(layers, 'water', 'fill-color');
  assert.ok(earth !== null && water !== null);

  const ratio = contrastRatio(earth, water);
  assert.ok(ratio >= 1.35, `sea and land are only ${ratio.toFixed(2)}:1 apart`);
  // And the land must be the lighter one: unexplored ground, not a void.
  assert.ok(contrastRatio(earth, '#000000') > contrastRatio(water, '#000000'));
});

test('the hillshade is present and carries more weight than in the light style', () => {
  // If this layer ever goes missing the style still renders, still looks
  // plausible, and has lost its figure-ground entirely (D-026, D-035).
  for (const name of ['dark', 'light'] as const) {
    const hillshade = style(name).layers.find((layer) => layer.type === 'hillshade');
    assert.ok(hillshade !== undefined, `${name} has no hillshade layer`);
  }

  const dark = style('dark').layers.find((layer) => layer.type === 'hillshade');
  const light = style('light').layers.find((layer) => layer.type === 'hillshade');
  const exaggeration = (layer: Layer | undefined): number =>
    Number(layer?.paint?.['hillshade-exaggeration'] ?? 0);

  assert.ok(
    exaggeration(dark) > exaggeration(light),
    'a dark ground swallows relief — it needs more exaggeration, not the same'
  );
});

// ---------------------------------------------------------------------------
// Labels, and headroom for the trace
// ---------------------------------------------------------------------------

test('place labels are unambiguous over both sea and land', () => {
  const layers = style('dark').layers;
  const earth = layerColour(layers, 'earth', 'fill-color');
  const water = layerColour(layers, 'water', 'fill-color');
  assert.ok(earth !== null && water !== null);

  const labels = layers.filter(
    (layer) => layer.type === 'symbol' && layer.paint?.['text-color'] !== undefined
  );
  assert.ok(labels.length > 0, 'no label layers found — the probe is wrong');

  const grounds: string[] = [earth, water];
  for (const label of labels) {
    const colour = flatColour(label, 'text-color');
    if (colour === null) {
      continue;
    }
    for (const ground of grounds) {
      const ratio = contrastRatio(colour, ground);
      assert.ok(ratio >= 7, `${label.id} ${colour} is ${ratio.toFixed(2)}:1 on ${ground}`);
    }
  }
});

test('nothing in the basemap takes the brightness the trace needs', () => {
  // ⚠ The whole purpose of the dark style (design brief §2.3): the user's own
  // trace must be unambiguously the brightest thing on screen. Labels are
  // exempt — they are text, they are sparse, and they are meant to be read.
  const layers = style('dark').layers;
  const earth = layerColour(layers, 'earth', 'fill-color');
  assert.ok(earth !== null);

  const tooBright: string[] = [];
  for (const layer of layers) {
    if (layer.type === 'symbol' || layer.type === 'hillshade') {
      continue;
    }
    for (const property of ['fill-color', 'line-color', 'background-color']) {
      const colour = flatColour(layer, property);
      if (colour === null) {
        continue;
      }
      // 6:1 against the ground leaves the top of the range free for the trace.
      const ratio = contrastRatio(colour, earth);
      if (ratio > 6) {
        tooBright.push(`${layer.id} ${colour} at ${ratio.toFixed(2)}:1`);
      }
    }
  }

  assert.deepEqual(
    tooBright,
    [],
    'these compete with the trace for the brightest thing on the map'
  );
});
