/**
 * Turn a bundled style template into a style the renderer can load (T-056).
 *
 * The templates in `assets/map/{light,dark}.json` are generated by
 * `tiles/style/generate.mjs` — never edited here, never edited by hand
 * (docs/map-style.md). They arrive with three placeholders, because at
 * generation time nobody can know where on a particular phone the files will
 * land. This module substitutes the real URIs discovered by `mapAssets.ts`.
 *
 * String replacement on the serialised JSON is deliberate, not lazy: the
 * placeholders are unique quoted strings, the output stays a plain string —
 * which is exactly what the MapView wants — and nothing here needs to
 * understand the style's structure to do its job.
 */

import darkTemplate from '../../assets/map/dark.json';
import lightTemplate from '../../assets/map/light.json';
import type { MapAssetUris } from './mapAssets';

export type MapStyleName = 'light' | 'dark';

export function buildMapStyle(name: MapStyleName, uris: MapAssetUris): string {
  const template = name === 'light' ? lightTemplate : darkTemplate;
  return JSON.stringify(template)
    .replaceAll('{{TILES_PMTILES}}', uris.tilesUrl)
    .replaceAll('{{TERRAIN_PMTILES}}', uris.terrainUrl)
    .replaceAll('{{GLYPHS}}', uris.glyphsRoot);
}
